### ISSUE TITLE
Создание реального макета теплицы

### ISSUE THREAD

**Issue by MthW01** [MthW01/Smart-greenhouse#19]

**Comment by zEvilCube** [comment]
[https://drive.google.com/drive/folders/1XHGhgCt6R3h4k3oWGfK2O5T37_-yVjAa?usp=sharing](https://vk.com/away.php?to=https%3A%2F%2Fdrive.google.com%2Fdrive%2Ffolders%2F1XHGhgCt6R3h4k3oWGfK2O5T37_-yVjAa%3Fusp%3Dsharing&cc_key=)
